### ISSUE TITLE
Results on ScanNet (pretrained checkpoint)

### ISSUE THREAD

**Issue by kentangSJTU** [facebookresearch/votenet#11]
Hi authors,

Thanks a lot on your work and code for VoteNet. After installing the code, preparing the dataset according to instructions and evaluating with the provided pretrained checkpoint on ScanNet (running the script `python eval.py` with given flags in README.md), I got the following output:

(*PS: Some duplicate numbers are removed.*)

---------- iou_thresh: 0.250000 ----------
eval cabinet Average Precision: 0.368814
eval bed Average Precision: 0.887401
eval chair Average Precision: 0.890175
eval sofa Average Precision: 0.893592
eval table Average Precision: 0.589219
eval door Average Precision: 0.457754
eval window Average Precision: 0.376980
eval bookshelf Average Precision: 0.456502
eval picture Average Precision: 0.059759
eval counter Average Precision: 0.562570
eval desk Average Precision: 0.665162
eval curtain Average Precision: 0.465986
eval refrigerator Average Precision: 0.502340
eval showercurtrain Average Precision: 0.594321
eval toilet Average Precision: 0.975494
eval sink Average Precision: 0.444091
eval bathtub Average Precision: 0.889807
eval garbagebin Average Precision: 0.381119
**eval mAP: 0.581172**
eval cabinet Recall: 0.758065
eval bed Recall: 0.950617
eval chair Recall: 0.928363
eval sofa Recall: 0.989691
eval table Recall: 0.837143
eval door Recall: 0.710921
eval window Recall: 0.624113
eval bookshelf Recall: 0.844156
eval picture Recall: 0.234234
eval counter Recall: 0.865385
eval desk Recall: 0.929134
eval curtain Recall: 0.701493
eval refrigerator Recall: 0.964912
eval showercurtrain Recall: 0.857143
eval toilet Recall: 1.000000
eval sink Recall: 0.622449
eval bathtub Recall: 0.935484
eval garbagebin Recall: 0.688679
eval AR: 0.802332

---------- iou_thresh: 0.500000 ----------
eval cabinet Average Precision: 0.077516
eval bed Average Precision: 0.824878
eval chair Average Precision: 0.676398
eval sofa Average Precision: 0.705267
eval table Average Precision: 0.423883
eval door Average Precision: 0.158062
eval window Average Precision: 0.074264
eval bookshelf Average Precision: 0.307388
eval picture Average Precision: 0.008684
eval counter Average Precision: 0.117078
eval desk Average Precision: 0.341620
eval curtain Average Precision: 0.217135
eval refrigerator Average Precision: 0.309121
eval showercurtrain Average Precision: 0.044384
eval toilet Average Precision: 0.874484
eval sink Average Precision: 0.233770
eval bathtub Average Precision: 0.820859
eval garbagebin Average Precision: 0.137844
**eval mAP: 0.352924**
eval cabinet Recall: 0.368280
eval bed Recall: 0.864198
eval chair Recall: 0.760965
eval sofa Recall: 0.824742
eval table Recall: 0.605714
eval door Recall: 0.364026
eval window Recall: 0.166667
eval bookshelf Recall: 0.610390
eval picture Recall: 0.036036
eval counter Recall: 0.307692
eval desk Recall: 0.700787
eval curtain Recall: 0.283582
eval refrigerator Recall: 0.684211
eval showercurtrain Recall: 0.214286
eval toilet Recall: 0.913793
eval sink Recall: 0.316327
eval bathtub Recall: 0.870968
eval garbagebin Recall: 0.347170
eval AR: 0.513324

If my understanding is correct, the performance of VoteNet seems to be mAP=58.12% at IoU=0.25, mAP=35.29% at IoU=0.5, which is significantly higher than what is reported in the paper. Is there anything wrong with my understanding on the results? Thanks a lot for your answer.

Best,
Ken

**Comment by NUAAXQ** [comment]
You should download the newest version of paper [here](https://arxiv.org/pdf/1904.09664.pdf)

**Comment by kentangSJTU** [comment]
> You should download the newest version of paper [here](https://arxiv.org/pdf/1904.09664.pdf)

Oh, thanks a lot for pointing out~ I would close this issue since the results match with the latest version of the paper.
