### ISSUE TITLE
Training on custom data, only the first object in the list is ever trained

### ISSUE THREAD

**Issue by damonftl** [facebookresearch/votenet#113]
I have created my own dataloader and I'm successfully training VoteNet on my data. Things appear to work, but only one object ever gets actually trained in, and it's always the first one in the list. I'm trying with two or three objects, and even when I switch their order in the list, it still only ever gets the first one. Here's a batch going through training so you can see the values output, and things look okay. These are just in the first epoch, so that's why it looks so bad:

```
 ---- batch: 010 ----
mean box_loss: 0.561006
mean center_loss: 0.207614
mean heading_cls_loss: 2.056063
mean heading_reg_loss: 0.030713
mean loss: 17.246320
mean neg_ratio: 0.713672
mean obj_acc: 0.860593
mean objectness_loss: 0.144644
mean pos_ratio: 0.059570
mean sem_cls_loss: 0.683496
mean size_cls_loss: 0.900661
mean size_reg_loss: 0.027006
mean vote_loss: 1.022955
```

As it trains, the numbers appear to do what they should. And then, when I get to an eval phase, when it calculates average precisions, this is what I see:

```
Eval batch: 10
eval mean box_loss: 0.463892
eval mean center_loss: 0.242243
eval mean heading_cls_loss: 0.987535
eval mean heading_reg_loss: 0.024332
eval mean loss: 16.180108
eval mean neg_ratio: 0.658729
eval mean obj_acc: 0.869922
eval mean objectness_loss: 0.150041
eval mean pos_ratio: 0.075721
eval mean sem_cls_loss: 0.108614
eval mean size_cls_loss: 0.700695
eval mean size_reg_loss: 0.028494
eval mean vote_loss: 1.068237
D:\votenet\utils\eval_det.py:154: RuntimeWarning: invalid value encountered in true_divide
  rec = tp / float(npos)
D:\votenet\utils\eval_det.py:154: RuntimeWarning: invalid value encountered in true_divide
  rec = tp / float(npos)
0 0.024822130858915763
1 nan
2 nan
eval object1 Average Precision: 0.024822
eval object2 Average Precision: nan
eval object3 Average Precision: nan
eval mAP: nan
eval object1 Recall: 0.600000
eval object2 Recall: nan
eval object3 Recall: nan
eval AR: nan
```

In my custom data class, if I switch object1 with object2 in the list at the top (`DEFAULT_TYPE_WHITELIST = ['object2', 'object1', 'object3]`) and in the other files (object_utils.py and model_utils_object.py) then object2 works fine and object1 and object3 gets the nan average precision. It always seems to only work with just the object in the first position of the list. I have double-checked my annotations and the data itself, and it appears like the correct data is going to the network training. That is, the data returned by my __getitem__() function does contain all the object labels and data. Has anyone else come across something like this? What can I do to narrow down what could be causing this? I'm glad to post more data if it would help.

**Comment by damonftl** [comment]
I ended up figuring this out on my own. In case others come across this kind of problem: the issue was in my dataset's `__getitem__(self, idx)` method, where I was not returning consistent size classes for the objects. Now it is training on all my objects, though the AP at the end is terrible, so I still have work to go. I think it has something to do with the size and angle classes, which I am not really using but the data still getting trained with them (pretty much just either 0 or 1 for those). I think I need to figure out how to take that stuff out of training so it'll just use bounding boxes and semantic classes.

**Comment by rXYZkit** [comment]
For me, this is because the `self.num_class`, `self.num_size_cluster`, `self.type2class` aren't correct.

**Comment by madinwei** [comment]
hello @rXYZkit 
I am using two classes, so how I should set up self.num_class, self.num_size_cluster, self.type2class and also self.num_heading_bin. I would be thankful for any help.
