### ISSUE TITLE
Error when runing extract_rgbd_data_v2.m

### ISSUE THREAD

**Issue by DCNSW** [facebookresearch/votenet#117]
I have download the SUNRGBDMeta2DBB_v2.mat and SUNRGBDMeta3DBB_v2.mat from official_url . But the code cannot pass the assertion when running extract_rgbd_data.m.
@charlesq34

logs:

imageId =
2

ans =
bed

classname =
bed

ans =
night_stand

classname =
night_stand

ans =
pillow

classname =
lamp

Error using extract_rgbd_data_v2 (line 79)
Assertion failed.

**Comment by madinwei** [comment]
@DCNSW  hello, have you fixed this error?
