### ISSUE TITLE
Why training on SUN rgbd v1 rather than v2?

### ISSUE THREAD

**Issue by BigDeviltjj** [facebookresearch/votenet#12]
Hi, I visualized the 3d label boxes of sunrgbd V1 and found that there were some unreasonable 3d label boxes which contained the whole scene with "table" label. While there was no such problem in sunrgbd v2.

Could you please tell me why you utilized v1 as training and testing set rather than v2?

**Comment by jytime** [comment]
If I remember it correctly, Charles mentioned this in F-Pointnet that they use sunrgbd v1 simply to make comparison with previous methods' results.

I notice that sunrgbd v1 also includes other types of weird labels. My observation is, these weird labels would result in quite bad AP for 'table' and 'desk' categories. However,  the trend of these two categories' AP is consistent with others. If a method can obviously improve other categories' AP, it would also work on 'table' and 'desk'.

**Comment by BigDeviltjj** [comment]
![webwxgetmsgimg](https://user-images.githubusercontent.com/38883913/64115960-942ffb00-cdc3-11e9-91d8-1dc9b27af981.jpeg)
@jytime Yes, there are many cases like the above example. The labels of V2 seems better.

**Comment by charlesq34** [comment]
Hi @BigDeviltjj 

As @jytime said, using V1 labels is mostly for a fair comparison with previous methods (which are trained and tested on V1 labels). The final mAP on V1 or V2 labels are similar though.
