### ISSUE TITLE
Generating the meta data for more ScanNet objects

### ISSUE THREAD

**Issue by daveredrum** [facebookresearch/votenet#13]
Hi there,

I'm wondering if there's any way to generate a new "scannet_means.npz" file for some more ScanNet objects? Currently, I'm trying to perform the object detection task via Votenet on more objects, but the "scannet_means.npz" only support objects from the 18 NYU40 classes.

I'd be very appreciative if someone can give me a hint. :)

Cheers,
Dave

**Comment by charlesq34** [comment]
Hi @daveredrum 

You can have a look in the `batch_load_scannet_data.py` file which prepares the scannet for our use. The object IDs specify the object categories we care about. You can extend this set as you like. Then once the dataset is prepared you can just go through the scenes (with `scannet_detection_dataset.py` in the training set to collect statistics on object box sizes.

https://github.com/facebookresearch/votenet/blob/257b8d8369511c6b4e0cea9c33ef0da01dd10f77/scannet/batch_load_scannet_data.py#L22

**Comment by daveredrum** [comment]
Thanks for the answer @charlesq34 

I tried to extend the `OBJ_CLASS_IDS ` but I still need to update the `scannet/meta_data/scannet_means.npz` accordingly, otherwise an error would occur. See this line:
https://github.com/facebookresearch/votenet/blob/257b8d8369511c6b4e0cea9c33ef0da01dd10f77/scannet/scannet_detection_dataset.py#L154
(where `DC. mean_size_arr` corresponds to `scannet/meta_data/scannet_means.npz`, if I'm not terribly mistaken.)

It seems that the `scannet/meta_data/scannet_means.npz` stores some mean values generated from the bounding boxes. Do you know how to generate that file?

**Comment by charlesq34** [comment]
The full steps are something like:

1. Run `batch_load_scannet_data.py` with the new OBJ_CLASS_IDS
2. Write some new script that uses `scannet_detection_dataset.py` to iterate through each scene in the training set and collect statistics on the bounding box sizes. Write the mean box sizes to a new npz file.
3. Use the new npz file and a new scannet config (adjust number of classes) to train the model.

Let me know if you have more questions.

**Comment by daveredrum** [comment]
That's great! Now it's working with more classes.

It seems after extending the `OBJ_CLASS_IDS`, the related parts in `scannet_detection_dataset.py` and `model_util_scannet.py` should also be updated accordingly.

I'm closing this issue. Thx a lot for the help! @charlesq34
