### ISSUE TITLE
process still killed when runing extract_rgbd_data_v2.m

### ISSUE THREAD

**Issue by cjhyy7190** [facebookresearch/votenet#14]
I ran this process on the server.Free memory is 16100MiB.After about 20 minutes，I got a Segmentation violation detected.And the process also killed.Before ran this process,I have 
already comment the SUNRGBD2Dseg.mat the scripts works.But the process still killed.The other two .m process can be run.
is there still anyway to skip this step for preparing SUN-RGB-D data?

**Comment by charlesq34** [comment]
Hi @cjhyy7190 can you find out the error?

You can change the `parfor` to `for` and then remove the try--catch--end lines, and then run the script again, to see what the error message is.

https://github.com/facebookresearch/votenet/blob/257b8d8369511c6b4e0cea9c33ef0da01dd10f77/sunrgbd/matlab/extract_rgbd_data_v2.m#L38

**Comment by cjhyy7190** [comment]
hello，I changed the code as you said.It mentioned me 'Error using extract_rgbd_data_v2 (line 75)  Assertion failed.' could you please tell me how can i do to change this error?thank you very much.

**Comment by cjhyy7190** [comment]
Hi, when i change the parfor to for and reserve the try--catch--end lines,the script can be run.Thank you very much!

**Comment by charlesq34** [comment]
Hi @cjhyy7190 

Line 75 verifies that the 2d bounding box class matches the 3d box class. It should pass the assertion if you are using the .mat files from the link I provided.

Maybe after you run the .m script, you can check to see if all the 10355 samples are successfully generated.

e.g. `ls sunrgbd_trainval/depth | wc` should return 10355.

**Comment by cjhyy7190** [comment]
Thank you very much .The problem has been solved after your reply.Thank you .

**Comment by DCNSW** [comment]
I have download the SUNRGBDMeta2DBB_v2.mat and SUNRGBDMeta3DBB_v2.mat from [official_url](http://rgbd.cs.princeton.edu/data/) . But the code cannot pass the assertion when running extract_rgbd_data.m.
@charlesq34

**Comment by cjhyy7190** [comment]
最近找到一个不防错的扑克站，春节辨没事就过来消遣吧纠，我今年春节的红包就靠它了，哈哈，http://www.sqp6h1.cn

**Comment by GuardianWang** [comment]
For me, the error is `Can't reload '....../matlab/R2018a/bin/glnxa64/libmwxcp_dwarf.so'` when calling `im2double`. 

One solution is to rename `libmwxcp_dwarf.so` to something else. But I don't have root access.
To fix this, I modified line 10 of `../OFFICIAL_SUNRGBD/SUNRGBDtoolbox/readData/read3dPoints` to `rgb = double(im) / 255`

**Comment by cjhyy7190** [comment]
最近找到一个不防错的扑克站，春节辨没事就过来消遣吧纠，我今年春节的红包就靠它了，哈哈，http://www.sqp6h1.cn
