### ISSUE TITLE
some questions about the final figure

### ISSUE THREAD

**Issue by iamnotstory** [facebookresearch/votenet#16]
Thanks for your excellent work! I got a very high precision than before.But I have some questions about the figure.When I finish run the eval.py ,I got some files like this:
![image](https://user-images.githubusercontent.com/28826593/64471593-2bab9a00-d186-11e9-8067-33098f3f6566.png)
and could you please tell me how can I do to get the final figure in the paper you show?thank you

**Comment by cjhyy7190** [comment]
hello, have you solved this problem? when i open the .obj file, it mentioned me 'No Vertex Found'. do you know something about it ?

**Comment by charlesq34** [comment]
Hi @iamnotstory 

`*_pc.ply` shows the input point cloud.
`*_pred_confident_nms_bbox.ply` shows the predicted 3d bounding box (the confident ones, pruned by NMS)
`*_gt_bbox.ply` shows the ground truth 3d bounding boxes.
`*_pred_map_cls.txt` records the predicted 3d bounding box parameters and confidence scores.

The rest `.ply` files are for debugging purposes. E.g. `seed_pc` are the seed points, `vgen_pc` shows the predicted votes.

After you load such files in MeshLab, you can set the colors for each set of point clouds or bounding boxes. See [here](https://github.com/facebookresearch/votenet/issues/3#issuecomment-525400801) on how to set quad-mesh mode for bounding boxes.
