### ISSUE TITLE
Model convert issues

### ISSUE THREAD

**Issue by 44825762** [facebookresearch/votenet#165]
Hi, I am converting the model to onnx model using a checkpoint whcih trained 180 epochs, the grouped_feature result is very similar but when the grouped_feature get through MLP in SA, the result is very difference. 
Does any one know how to fix this?  The result of checkpoint is correct.
Or does any one has a converted onnx or ncnn model?

**Comment by jkstyle2** [comment]
@44825762 hi, i have a similar issue with conversion to onnx model. Have you fixed the issue?
