### ISSUE TITLE
What's the direction of rotation you specify on SUN-RGBD dataset,  it is clockwise or counterclockwise?

### ISSUE THREAD

**Issue by happiensslz** [facebookresearch/votenet#20]
In the 121 line of the sunrgbd_detection_dataset.py:

def rotz(t):
"""Rotation about the z-axis."""
c = np.cos(t)
s = np.sin(t)
return np.array([[c, -s, 0],
[s, c, 0],
[0, 0, 1]])

rot_mat = sunrgbd_utils.rotz(rot_angle)
bboxes[:,6] -= rot_angle (Line 121)

Why not bboxes[:,6] += rot_angle ?

**Comment by happiensslz** [comment]
In the 121 line  of the sunrgbd_detection_dataset.py:

def rotz(t):
    """Rotation about the z-axis."""
    c = np.cos(t)
    s = np.sin(t)
    return np.array([[c, -s,  0],
                     [s,  c,  0],
                     [0,  0,  1]])

 rot_mat = sunrgbd_utils.rotz(rot_angle)
 bboxes[:,6] -= rot_angle (Line 121)

Why not  bboxes[:,6] += rot_angle ?

**Comment by charlesq34** [comment]
Hi @happiensslz 

The heading angle is rotation angle from +X to -Y (clockwise).  +X is 0 degree, -Y is 90 degree (in the upright depth coordinate system: Z is up-axis, X points to right, Y points forward).

You can refer to the comment here for more details (note for box dumping, we multiply the heading_angle with -1 to make it consistent with the `write_oriented_bbox` API):
https://github.com/facebookresearch/votenet/blob/257b8d8369511c6b4e0cea9c33ef0da01dd10f77/sunrgbd/sunrgbd_data.py#L128

**Comment by happiensslz** [comment]
@charlesq34  Thank you for your patience to answer!
