### ISSUE TITLE
Related work

### ISSUE THREAD

**Issue by JJJJY-rgb** [facebookresearch/votenet#21]
Thanks for your great job!this net is so wonderful.And I want to know , if the votenet has been well trained , can we use it to detect other poind clouds(such as we get the point cloud from the reconstruction work) , and Where should I modify the code?I look forward to your reply.Thank you.

**Comment by charlesq34** [comment]
Hi @JJJJY-rgb 

You can refer to the `demo.py` on how to use the model to detect objects. Just make sure the point clouds are in real metric space (distance between points follow the physical world) and the coordinate system is right (Z up, X right, Y forward).

**Comment by toshk15** [comment]
Hi @charlesq34 
Could with the Demo read files with .pcd or .bin files?
My question is because
![pcd](https://user-images.githubusercontent.com/45886706/64740966-99c0cb80-d4bc-11e9-9d38-9746e02a1674.png)
 these files come with the following information apart from the x, y z coordinates.

**Comment by charlesq34** [comment]
As the network is trained with XYZ coordinates of points only, it does not support extra features such as intensity for now.

In terms of data loading, I think you can easily find some I/O python code online.

One more thing to note is that the demo will subsample the point cloud to 40,000 points (assuming you are using the model trained on ScanNet).

**Comment by toshk15** [comment]
HI @charlesq34 

How much RAM does my computer need to load the file extract_rgbd_data_v2.m?
Could you share the specifications of your machine?
thanks!

**Comment by charlesq34** [comment]
Hi @toshk15 

the requirement is minimum I think as you don't need to hold the entire dataset in memory.

I used my own laptop with memory of 32GB.

**Comment by charlesq34** [comment]
I've written a small doc explaining how to modify the code to support training on your own data: https://github.com/facebookresearch/votenet/blob/master/doc/tips.md

Closing this thread due to lack of activity.
