### ISSUE TITLE
Size class label and semantic class label

### ISSUE THREAD

**Issue by jytime** [facebookresearch/votenet#24]
Hi,

According to the codes below, it seems that size regression is coupled with semantic classification. The size class label is the same as the semantic class label. I guess this is under the assumption that templates (average size) can provide a strong proposal.

I just wanna check if I misunderstand something. Please correct me if I'm wrong.

https://github.com/facebookresearch/votenet/blob/257b8d8369511c6b4e0cea9c33ef0da01dd10f77/sunrgbd/sunrgbd_detection_dataset.py#L169

https://github.com/facebookresearch/votenet/blob/257b8d8369511c6b4e0cea9c33ef0da01dd10f77/sunrgbd/model_util_sunrgbd.py#L38-L42

Best,
Jianyuan

**Comment by charlesq34** [comment]
HI @jytime 

Your understanding is right. We assumed that the size class is the same as the object class. It could be wrong in some cases (like a huge table, whose size may be closer to the bed template) but is in general okay. You can also decouple this relationship and experiment with more size templates. Let us know if it helps significantly!

**Comment by jytime** [comment]
Hi,
Currently, I have not found a significant boost. I will update this if I find it later.
Best
