### ISSUE TITLE
Some question about sunrgb

### ISSUE THREAD

**Issue by JMU-HSF** [facebookresearch/votenet#26]
Hi, when I run the extract_rgbd_data_v2.m, the load('SUNRGBD2Dseg.mat') always is faild. Could you help me? Thank you very much.

**Comment by toshk15** [comment]
I have the same problem, matlab stops my laptop, so I asked the requirements because I only have 24 GB of RAM

**Comment by charlesq34** [comment]
HI @JMU-HSF , @toshk15 

Loading SUNRGBD2Dseg is optional -- I have updated the matlab script (removed loading SUNRGBD2DSeg). This should solve the memory issue.
