### ISSUE TITLE
some problem about the figure

### ISSUE THREAD

**Issue by WangZhouTao** [facebookresearch/votenet#3]
Thank you very much for your good work. I want to know which software did you use to get the figure in the paper? mayavia 、meshlab or another one？
![webwxgetmsgimg](https://user-images.githubusercontent.com/9363268/63778417-52143e80-c917-11e9-9b91-5d40c7a7dceb.jpeg)

**Comment by NUAAXQ** [comment]
@charlesq34 Thanks very much for sharing. So the color is computed in advance before imported into MeshLab, or colorized by some function in MeshLab?

**Comment by WangZhouTao** [comment]
Thank you for your reply,

**Comment by raghavgurbaxani** [comment]
Hi @charlesq34 & @orlitany 

Thank you for your amazing work on this project. I am having some trouble visualizing the way depicted in the paper.

After turning into quad dominant mesh, I get something like this - 

![image](https://user-images.githubusercontent.com/32988039/67330098-b515f200-f4d0-11e9-9bac-1926f91953a5.png)

How shall I proceed towards visualizations as depicted in the paper ? I.E. having the hollow boxes as well as different colors for the point clouds ? 

Also, how do I generate the text file that recognizes which objects are in the scene (ie chair, table,etc) and not just the bounding boxes. 

Thank you in advance.

**Comment by raghavgurbaxani** [comment]
@WangZhouTao Were you able to get the figure ?

**Comment by LZQ1204** [comment]
> Hi @NUAAXQ No problem.
> 
> The color is written in advance into the PLY file. You can refer to the `write_ply_rgb` here
> 
> https://github.com/facebookresearch/votenet/blob/257b8d8369511c6b4e0cea9c33ef0da01dd10f77/utils/pc_util.py#L229
> 
> We used matplotlib's colormap.

Hello, can I add color information during training and see the color of point cloud during visualization:
 CUDA_VISIBLE_DEVICES=0 python train.py --dataset sunrgbd --log_dir log_sunrgbd --use_color
