### ISSUE TITLE
Visualization of Groundtruth

### ISSUE THREAD

**Issue by WangZhouTao** [facebookresearch/votenet#31]
hi, I downloaded the code and trained. I wanted to compare the detection result of the model with GT. I use [https://github.com/facebookresearch/votenet/blob/257b8d8369511c6b4e0cea9c33ef0da01dd10f77/scannet/data_viz.py](url) for visualization. But some error happened:
`AttributeError: 'ScannetDatasetConfig' object has no attribute 'param2bbox'`
Do you know where this function is? Or how should I visualize Ground-Truth?

**Comment by charlesq34** [comment]
Hi @WangZhouTao 

that's a good catch! the code was using some old function which was not included in this repo. I've removed those lines to avoid confusion.

Instead, you can run [`scannet_detection_dataset.py`](https://github.com/facebookresearch/votenet/blob/master/scannet/scannet_detection_dataset.py) to visualize the boxes.

**Comment by WangZhouTao** [comment]
thank for your reply. I can get the result I want.
