### ISSUE TITLE
The number of provided proposals using 'per_class_proposal'

### ISSUE THREAD

**Issue by jytime** [facebookresearch/votenet#35]
Hi Charles,

I am a bit confused about 'per_class_proposal'. According to Figure 8 in the Votenet paper, it seems that we should assign each proposal to all the 10 classes, pick top K ranked (e.g., 256) proposals, and then NMS.

Meanwhile the released codes duplicate proposals after NMS to 10 classes and look somehow different from paper's description. Please correct me if I misunderstand something.

https://github.com/facebookresearch/votenet/blob/257b8d8369511c6b4e0cea9c33ef0da01dd10f77/models/ap_helper.py#L169-L179

**Comment by charlesq34** [comment]
Hi @jytime 

It is the expected behavior to duplicate proposals to all classes. It is as if we have a per-class detector.

Which place in paper do you notice that the description to be different from the implementation?

**Comment by jytime** [comment]
ok I misunderstand Figure 8. I thought the horizontal axis 'NUMBER OF PROPOSALS' means the proposals fed into NMS or mAP evaluation.

Thanks a lot for your reply.
