### ISSUE TITLE
Model size and inference speed

### ISSUE THREAD

**Issue by dashidhy** [facebookresearch/votenet#38]
Dear authors,

I was wondering how do you compute your model size and inference speed (Table 4 in paper) ? Thanks!

**Comment by charlesq34** [comment]
For model size we just checked the stored pytorch file size. For the inference speed, we wrote some script to infer detection for a batch with batch size 1 and measure the time.
There might be better Pytorch utils to time the inference speed though.

**Comment by madinwei** [comment]
@charlesq34 , thank you for this valuable model, is it possible if you can share the inference code?
