### ISSUE TITLE
Final Images- as In Paper

### ISSUE THREAD

**Issue by raghavgurbaxani** [facebookresearch/votenet#39]
Hi @charlesq34 & @orlitany 

Thank you for your amazing work on this project. I am having some trouble visualizing the way depicted in the paper.

After turning into quad dominant mesh, I get something like this - 

![image](https://user-images.githubusercontent.com/32988039/67330098-b515f200-f4d0-11e9-9bac-1926f91953a5.png)

How shall I proceed towards visualizations as depicted in the paper ? I.E. having the hollow boxes as well as different colors for the point clouds ? 

Also, how do I generate the text file that recognizes which objects are in the scene (ie chair, table,etc) and not just the bounding boxes. 

Thank you in advance.

**Comment by charlesq34** [comment]
Hi @raghavgurbaxani 

You can check this thread for the MeshLab setting: https://github.com/facebookresearch/votenet/issues/1

Also just search Meshlab in the issues section will lead you to some other discussion.
For texts, I think it's currently not supported. If you have Linux machines, you can also use mayavi python package for the visualization, which supports writing texts.

**Comment by raghavgurbaxani** [comment]
@charlesq34  

I followed the issues #1 and #16 

this is the figure I obtain - 

![image](https://user-images.githubusercontent.com/32988039/68418485-2bf7ef80-014d-11ea-8036-db029d3f7022.png)



How do I get hollow bounding boxes ? Like here -
![image](https://user-images.githubusercontent.com/32988039/68418564-52b62600-014d-11ea-823f-35be86e5d49b.png)

**Comment by gkd2020** [comment]
> @charlesq34
> 
> I followed the issues #1 and #16 and this is the figure I obtain -
> 
> ![image](https://user-images.githubusercontent.com/32988039/68418485-2bf7ef80-014d-11ea-8036-db029d3f7022.png)
> 
> How do I get hollow bounding boxes ? Like here -
> ![image](https://user-images.githubusercontent.com/32988039/68418564-52b62600-014d-11ea-823f-35be86e5d49b.png)
> 
> also I can try to visualize the text on the bounding boxes, but how do I extract the predicted object classes ? Is there a text file generated with the predicted objects.
> 
> thanks in advance :)

hi,I meet the same problem. Do you know how to display the colored hollow frame in votenet's paper? The following figure is the result I obtained. It looks strange.I will be looking forward to your reply.
![2020-02-25 16-12-54屏幕截图](https://user-images.githubusercontent.com/59494593/75227735-b726ef00-57e9-11ea-9e46-cea2f99bfa1f.png)

**Comment by zhanghm1995** [comment]
@chenyu-zhai Hi, did you solve the visualization problem? I also encounter the same problem with you.
I don't know how to visualize the hollow bounding boxes results like the paper.

**Comment by NUAAXQ** [comment]
> @chenyu-zhai Hi, did you solve the visualization problem? I also encounter the same problem with you.
> I don't know how to visualize the hollow bounding boxes results like the paper.

@zhanghming [this link](https://github.com/NUAAXQ/MLCVNet#detections-visualization) may be helpful for you.
