### ISSUE TITLE
How is the value of K (the number of clusters) determined ?

### ISSUE THREAD

**Issue by jingnanshi** [facebookresearch/votenet#43]
Hi,

Thank you for sharing this repo. I'm wondering how did you select the value for K --- the number of clusters, which I think is the parameter `num_proposal` in the `VoteNet` class, but correct me if I'm wrong. 

Is it just an arbitrary fixed number? Have you guys observed any performance changes if modifying this parameter?

Thanks!

**Comment by jytime** [comment]
I think you are looking for Figure 8 in the paper. And in my experience, on sun rgbd and scannet dataset, as long as num_proposal is set high enough (e.g., >50), the performance would be fine

**Comment by jingnanshi** [comment]
@jytime Thank you! That makes sense.
