### ISSUE TITLE
Upgrading to PyTorch 1.3

### ISSUE THREAD

**Issue by victoryc** [facebookresearch/votenet#46]
Your Readme file says "Note: there is some incompatibility with newer version of Pytorch (e.g. v1.3), which is to be fixed". 

Are you planning to do that in the near future?

My motivation to upgrade to the latest version of Pytorch (1.3) is that as of now, the following error message pops up sporadically while training votenet. Based on searching on the internet, this error seems to have been fixed with the latest version of Pytorch.

 File "...l\Continuum\anaconda3\envs\votenet\lib\site-packages\torch\serialization.py", line 580, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 8 more bytes. The file might be corrupted.

**Comment by charlesq34** [comment]
A Pull Request merge solves the issue.
