### ISSUE TITLE
Color bounding boxes

### ISSUE THREAD

**Issue by dashidhy** [facebookresearch/votenet#47]
Dear authors,

I was wondering in Meshlab how can I assign different colors to bounding boxes within different semantic classes, like the way you did in your paper? The following picture is what I can get now and it's quite annoying all the bounding boxes are in the same color.

Thanks in advance!

![snapshot00](https://user-images.githubusercontent.com/24664403/68525470-aed09580-0286-11ea-9ef1-ee23eb3777ef.png)

**Comment by raghavgurbaxani** [comment]
@dashidhy how do you get the hollow bounding boxes ? I get them as a solid mesh

**Comment by dashidhy** [comment]
> @dashidhy how do you get the hollow bounding boxes ? I get them as a solid mesh

**Comment by dashidhy** [comment]
> @dashidhy how do you get the hollow bounding boxes ? I get them as a solid mesh

Hello, you may find #3 #16 helpful.

**Comment by cjhyy7190** [comment]
Hello, I wonder how can you get the bounding box so accurately?Which parameters do you adjust to?I also use the votenet to detect my own pointcloud , but I can't get so accurate bounding boxes as yours. They are also very terrible like this. One sofa can be detected as many things. Thank you for your reply.
![image](https://user-images.githubusercontent.com/54897131/69007806-ad395880-097d-11ea-884e-5fc9ef988481.png)

**Comment by tskuo** [comment]
Hi @dashidhy and the authors,

The image below is the point clouds and bounding boxes I got by following the discussions on Github. I am wondering how could I get the similar result as shown above in @dashidhy's post, where each point is assigned its corresponding color as in the original RGB image? Thank you for answering!
<img width="412" alt="Screen Shot 2019-11-19 at 1 07 28 AM" src="https://user-images.githubusercontent.com/19288447/69132513-12b64380-0a69-11ea-980b-c55be0c1521f.png">

**Comment by lyp0413** [comment]
@cjhyy7190  Hello to see you again.
You can try to set a lower 'nms_iou' and a higher 'conf_thresh' in eval_config_dict.

**Comment by cjhyy7190** [comment]
> @cjhyy7190 Hello to see you again.
> You can try to set a lower 'nms_iou' and a higher 'conf_thresh' in eval_config_dict.

thank you very much! I will try it again.

**Comment by J0KERCHANCE** [comment]
> Dear authors,
> 
> I was wondering in Meshlab how can I assign different colors to bounding boxes within different semantic classes, like the way you did in your paper? The following picture is what I can get now and it's quite annoying all the bounding boxes are in the same color.
> 
> Thanks in advance!
> 
> ![snapshot00](https://user-images.githubusercontent.com/24664403/68525470-aed09580-0286-11ea-9ef1-ee23eb3777ef.png)

Hi there,
I have got same problem here, have you found a solution to show different box colors for different object classes? Hope someone can help me out. Thank you in advance.

**Comment by cjhyy7190** [comment]
最近找到一个不防错的扑克站，春节辨没事就过来消遣吧纠，我今年春节的红包就靠它了，哈哈，http://www.sqp6h1.cn
