### ISSUE TITLE
can votenet be used to robot grasping?

### ISSUE THREAD

**Issue by YanqingWu** [facebookresearch/votenet#48]
I want to use the votenet to detect the pose of an object for robot grasping, so I want to know maybe the  accuracy is enough.

**Comment by charlesq34** [comment]
Hi @YanqingWu 

personally I haven't tried it on 6d pose estimation. but I think it is a very valuable direction for research!

you can refer to here on how to prepare your own data for 6d pose estimation: https://github.com/facebookresearch/votenet/blob/master/doc/tips.md

**Comment by YanqingWu** [comment]
> Hi @YanqingWu
> 
> personally I haven't tried it on 6d pose estimation. but I think it is a very valuable direction for research!
> 
> you can refer to here on how to prepare your own data for 6d pose estimation: https://github.com/facebookresearch/votenet/blob/master/doc/tips.md

@charlesq34 thanks, I will try.

**Comment by praj441** [comment]
> Hi @YanqingWu
> 
> personally I haven't tried it on 6d pose estimation. but I think it is a very valuable direction for research!
> 
> you can refer to here on how to prepare your own data for 6d pose estimation: https://github.com/facebookresearch/votenet/blob/master/doc/tips.md

Hi @charlesq34 , I have gone through the tips. I have a question.
Does size (l,w,h) are half of the actual box dimensions or they represent the full box sizes?
