### ISSUE TITLE
Get the class label for the predicted bounding boxes

### ISSUE THREAD

**Issue by jingnanshi** [facebookresearch/votenet#49]
Hi,

Can someone give some suggestions on how to get the object label for the predicted bounding boxes? I assume it should be in `*_pred_map_cls.txt` files, but I can't figure out how to interpret the parameters inside the text files. 

Thanks!

**Comment by charlesq34** [comment]
HI @jingnanshi If you read about how this file is written, you should find about the format.

specifically
here: https://github.com/facebookresearch/votenet/blob/da10b32212d0122d0140e4306c66a6aa0744fbae/models/dump_helper.py#L125

where batch_pred_map_cls is a list of lists [[(pred_cls, pred_box_params, score),...],...] described here: https://github.com/facebookresearch/votenet/blob/da10b32212d0122d0140e4306c66a6aa0744fbae/models/ap_helper.py#L56

**Comment by jingnanshi** [comment]
Hi @charlesq34 ,

Thank you for your prompt reply! I've parsed the files based on the description, and I have a few more questions that need confirmation:

1. The numbers of unique bounding boxes in `*_pred_map_cls.txt` files are not the same as  `*_pred_confident_nms_bbox.ply` files. From the code, it looks like the data in `*_pred_map_cls.txt` files are actually used for calculating AP values, and the dumped bounding boxes are for visualization only. Can you confirm this? 
2. For the results in paper, did you guys use `conf_thres` equals to 0.05? 

Thanks again for sharing the code, and answering my questions!
