### ISSUE TITLE
can votenet deal with overlapping objects cases ? 

### ISSUE THREAD

**Issue by jediofgever** [facebookresearch/votenet#54]
Hello @charlesq34 ,
thanks for your contributions. I was wondering whether votenet is able to perform in case of occlusions ?

**Comment by alar0330** [comment]
Yes, up to 3 overlapping bounding boxes.

**Comment by jediofgever** [comment]
hi @alar0330, do you have any sample results that show ? , it would be great to visually see

**Comment by alar0330** [comment]
I saw an example of that in one of the papers, either the one of VoteNet or PointNet++.
