### ISSUE TITLE
Question on the Scannet dataset

### ISSUE THREAD

**Issue by NUAAXQ** [facebookresearch/votenet#7]
For the training on ScanNet dataset, do we need to download the entire ScanNet release (1.3TB)?

**Comment by charlesq34** [comment]
Hi @NUAAXQ 

It is not necessary to download the entire ScanNet.
For example the RGB-D sensor stream files `*.sens` are not used, yet they account for majority of the size of the dataset (~80%).

So if you have limited disk space, you can download each scan separately and then delete the `*.sens` file.

Hope it helps.

**Comment by NUAAXQ** [comment]
@charlesq34 I got it. Thanks very much!

**Comment by gkd2020** [comment]
> Hi @NUAAXQ
> 
> It is not necessary to download the entire ScanNet.
> For example the RGB-D sensor stream files `*.sens` are not used, yet they account for majority of the size of the dataset (~80%).
> 
> So if you have limited disk space, you can download each scan separately and then delete the `*.sens` file.
> 
> Hope it helps.

Hi,@charlesq34,sorry to trouble you. 
The data set of scannet v2 is too big, and my hard disk space is not enough. 
If I do not download the `* .sens` file, I still need about 260G (1.3TB * 0.8). Is there any other files that I do not need to download?
