### ISSUE TITLE
Do SA2 to SA4 modules use the real farthest point sampling?

### ISSUE THREAD

**Issue by lilanxiao** [facebookresearch/votenet#73]
Hello, 
I have a question about the comments in line 114, 119 and 123 of backbone_module:
```
xyz, features, fps_inds = self.sa2(xyz, features) # this fps_inds is just 0,1,...,1023
...
xyz, features, fps_inds = self.sa3(xyz, features) # this fps_inds is just 0,1,...,511
...
xyz, features, fps_inds = self.sa4(xyz, features) # this fps_inds is just 0,1,...,255
```
Does it means these three modules don't really use farthest point sampling and just take the points with the index of [0: number_to_be_sampled]? It seems fine because each of these modules down samples the input points by factor 2. With such small factor, it's unnecessary to do the computational expensive FPS and taking some "random" points would be fairly enough.

Do I understand the code correctly?

Thank you!

**Comment by alar0330** [comment]
Have you noticed the in-line comments? Just like they suggest, as ALL indices are already FPS-ordered, the first N indices are still FPS-ordered. So yeah, it is "real" FPS for all SA-modules.

**Comment by lilanxiao** [comment]
> Have you noticed the in-line comments? Just like they suggest, as ALL indices are already FPS-ordered, the first N indices are still FPS-ordered. So yeah, it is "real" FPS for all SA-modules.

Ah! Thank your for reminding me! Yes, as you said, it's real FPS. The key point to understand it is the ORDER. When I opened this issue, I forgot how FPS works......
