### ISSUE TITLE
Problem with training VoteNet on own data

### ISSUE THREAD

**Issue by jonasf94** [facebookresearch/votenet#74]
I want to train VoteNet based on my own data. My data has only one class "box" and there is only one object per scene. I prepared everything like indicated in tips.md. However, i get bad results when training. Can anyone help me out? Here is the output from the training: 
![root@jfu: -home-jonas-Desktop-votenet_002](https://user-images.githubusercontent.com/33685239/74475137-2413be00-4ea7-11ea-9cca-c9bb88570b4a.png)

The metrics just get worse in the following epochs. 
Thanks!

**Comment by ccsone** [comment]
hello,How did you label the data set?

**Comment by madinwei** [comment]
@jo-chr Hello. I am trying also to use my custom data.  which annotation tool to use. please share with me if possible and thank you.

**Comment by jo-chr** [comment]
I ended up programming my own label tool: https://github.com/jo-chr/threed_od/tree/master/preprocessing.

However, there is an amazing new open source label tool for 3D CV: https://github.com/ch-sa/labelCloud
