### ISSUE TITLE
I can not get color  bounding box 

### ISSUE THREAD

**Issue by gkd2020** [facebookresearch/votenet#86]
Thank you for your excellent work. @charlesq34 My graduation project is to reproduce your thesis. 
I set up meshlab (wireframe, turn into quad domestic mesh) according to your suggestion, but I didn't get the color bounding box.
What's more,I can not open the` .obj` file.  Is my version of meshlab wrong? 
I look forward to your reply. I want to get the same beautiful picture as in your paper, please guide me, thank you very much
Here are some related contents in SUNRGB-D dataset: 
![2020-05-10 15-32-57屏幕截图](https://user-images.githubusercontent.com/59494593/81493603-57ae8a80-92d4-11ea-828e-609037b031de.png)
![snapshot00](https://user-images.githubusercontent.com/59494593/81493604-5c733e80-92d4-11ea-853f-f9112937d2c8.png)
![2020-05-10 15-40-05屏幕截图](https://user-images.githubusercontent.com/59494593/81493629-8dec0a00-92d4-11ea-8d5a-25eb849e0a1f.png)

----------
Today，I upgraded meshlab, but still didn't get the colored bounding box.
It seems that the "write_ply_color" function is not working. 

Save me,please
 Thank you

**Comment by chenyu-zhai** [comment]
Hi,@ jingnanshi ,sorry to trouble you again. I set up meshlab (wireframe, turn into quad domestic mesh) according to your suggestion, but I didn't get the color bounding box.Could you tell me where the problem is, thank you very much

**Comment by Caicaiyoko** [comment]
write_ply_rgb write_ply_color在util里，输入加上去就可以了应该，不过我没有验证，原理应该是给每个标签打颜色

**Comment by chenyu-zhai** [comment]
@Caicaiyoko 大佬，能说的更详细些吗，具体该修改哪里？
我看代码里用到了write_ply_rgb write_ply_color这两个函数，但是问答区所有结果的目标边界框都是没有颜色区分的。这两个函数好像不能工作，得到的结果和论文里展示的不一样。

**Comment by Caicaiyoko** [comment]
你不想想为什么不能工作么，你加个print进去别人根本就没工作啊，打开demo.py 看到 import pc_util没有，自己引入加进去应该就可以了(我没测试，这算法我只是稍微看下),自己多加几个print测试下

**Comment by chenyu-zhai** [comment]
大佬，作者在问答区说颜色是提前写入的，in advance，是我理解有问题吗。。。这给了我很大困扰
https://github.com/facebookresearch/votenet/issues/3#issuecomment-525430453
但是domo和eval跑完确实都没有颜色啊。。。demo确实也没引入write_ply_color

**Comment by Caicaiyoko** [comment]
> 大佬，作者在问答区说颜色是提前写入的，in advance，是我理解有问题吗。。。这给了我很大困扰
> [#3 (comment)](https://github.com/facebookresearch/votenet/issues/3#issuecomment-525430453)
> 但是domo和eval跑完确实都没有颜色啊。。。demo确实也没引入write_ply_color

ply格式可以是x,y,z,r,g,b 应该输入前处理了，自己通读下代码，问我没用，我只是在选择模型顺便看了下votenet，我不用这个。
