### ISSUE TITLE
error: ‘AT_CHECK’ was not declared in this scope

### ISSUE THREAD

**Issue by XunshanMan** [facebookresearch/votenet#97]
Hi, I met a problem and have solved it. Hope it helps those meeting the same problems.

**Environments:**

Ubuntu 16.04
Pytorch  1.6.0

**Problem description:**

Error comes out when running :
cd pointnet2
python setup.py install

_ext_src/include/utils.h:17:66: error: ‘AT_CHECK’ was not declared in this scope
AT_CHECK(x.is_contiguous(), #x " must be a contiguous tensor"); \

**Solve Methods:**

Replace the function names "AT_CHECK" to "AT_ASSERT" of the files under ./pointcloud2/.

All the files are shown as below. Recommend using VSCode to replace all of them at once.
![Screenshot from 2020-10-09 23-09-13](https://user-images.githubusercontent.com/13925978/95600104-8cda2700-0a84-11eb-9683-a07cdbd3a841.png)

**References:**
https://github.com/facebookresearch/votenet/issues/83
https://github.com/erikwijmans/Pointnet2_PyTorch/commit/1d5dca2673ee2831b9b01efe597b2ba8d12726f1

**Comment by hhd-shuai** [comment]
thanks

**Comment by hhd-shuai** [comment]
> Hi, I met a problem and have solved it. Hope it helps those meeting the same problems.
> 
> **Environments:**
> 
> Ubuntu 16.04
> Pytorch 1.6.0
> 
> **Problem description:**
> 
> Error comes out when running :
> cd pointnet2
> python setup.py install
> 
> _ext_src/include/utils.h:17:66: error: ‘AT_CHECK’ was not declared in this scope
> AT_CHECK(x.is_contiguous(), #x " must be a contiguous tensor"); \
> 
> **Solve Methods:**
> 
> Replace the function names "AT_CHECK" to "AT_ASSERT" of the files under ./pointcloud2/.
> 
> All the files are shown as below. Recommend using VSCode to replace all of them at once.
> ![Screenshot from 2020-10-09 23-09-13](https://user-images.githubusercontent.com/13925978/95600104-8cda2700-0a84-11eb-9683-a07cdbd3a841.png)
> 
> **References:**
> #83
> [erikwijmans/Pointnet2_PyTorch@1d5dca2](https://github.com/erikwijmans/Pointnet2_PyTorch/commit/1d5dca2673ee2831b9b01efe597b2ba8d12726f1)

thanks

**Comment by XunshanMan** [comment]
You're welcome, and I'll close this one.

**Comment by lijain** [comment]
You're welcome, and I'll close this one.
